services:
  - type: web
    name: linkedin-boost
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: resoboost  # Nom de votre nouvelle base
          property: connectionString
      - key: RENDER
        value: "true"
      - key: FLASK_ENV
        value: "production"
      - key: FLASK_DEBUG
        value: "0"
      - key: LINKEDIN_CLIENT_ID
        value: 86occjps58doir
      - key: LINKEDIN_CLIENT_SECRET
        value: WPL_AP1.C8C6uXjTbpJyQUx2.Y7COPg==
      - key: LINKEDIN_REDIRECT_URI
        value: https://linkedinboost.onrender.com/callback
      - key: GEMINI_API_KEY
        value: AIzaSyAH-hVzlQJQTCOLB1UsznxrObuY8XIsKMQ
      - key: PEXELS_API_KEY
        value: GRfBXoBp4ZxiaHejhH03WWpuSm07btLzWxyBq6Q9dnVFPr6BrJ8xpFlg

databases:
  - name: resoboost
    databaseName: resoboost
    user: resoboost_user
    region: frankfurt
    plan: basic

cron:
  - name: publish-scheduled-posts
    path: /publish_scheduled
    schedule: "*/10 * * * *"  # Toutes les 10 minutes
