services:
  - type: web
    name: linkedin-boost
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn appmin:app"  # Utilisez d'abord l'application minimale
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: boostdb_xv71
          property: connectionString
      - key: RENDER
        value: "true"  # Pour identifier l'environnement Render
      - key: FLASK_ENV
        value: "production"
      - key: FLASK_DEBUG
        value: "1"  # Activez le débogage temporairement
      - key: LINKEDIN_CLIENT_ID
        value: 86occjps58doir
      - key: LINKEDIN_CLIENT_SECRET
        value: WPL_AP1.C8C6uXjTbpJyQUx2.Y7COPg==
      - key: LINKEDIN_REDIRECT_URI
        value: https://linkedinboost.onrender.com/callback
      - key: GEMINI_API_KEY
        value: AIzaSyB434P__wR_o_rr5Q3PjOULqyKhMANRtgk
