services:
  - type: web
    name: linkedin-boost
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Boostdb  # nom de ta base Render
          property: connectionString
