# 🎯 ÉTAPES POUR DÉPLOYER SUR RENDER

# 1. MODIFIER requirements.txt (ajouter ces dépendances)
Flask==2.3.3
Flask-SQLAlchemy==3.1.1
requests==2.31.0
google-generativeai==0.3.2
psycopg2-binary==2.9.9
gunicorn==21.2.0
SQLAlchemy==2.0.23
Werkzeug==2.3.7  # 👈 IMPORTANT pour les mots de passe
urllib3==2.0.7
python-dotenv==1.0.0
Jinja2==3.1.3
itsdangerous==2.1.2
click==8.1.7
MarkupSafe==2.1.3

# 2. MODIFIER app.py (ajouter ces imports en haut)
from werkzeug.security import generate_password_hash, check_password_hash
from functools import wraps
import re
from datetime import datetime, timedelta

# 3. MODIFIER la fonction init_db() dans app.py
def init_db():
    """Initialiser la base de données avec les tables nécessaires"""
    with app.app_context():
        try:
            # Vérifier les tables existantes avant la création
            inspector = inspect(db.engine)
            existing_tables = inspector.get_table_names()
            logger.info(f"Tables existantes avant création: {existing_tables}")
            
            # Créer les tables si elles n'existent pas
            db.create_all()
            logger.info("Tables créées ou vérifiées avec succès")
            
            # 🔥 NOUVEAU : Créer un utilisateur admin par défaut sur Render
            if os.getenv("RENDER"):
                create_default_admin()
            
            # Vérifier les tables après création
            existing_tables = inspector.get_table_names()
            logger.info(f"Tables existantes après création: {existing_tables}")
            
        except Exception as e:
            logger.error(f"Erreur lors de l'initialisation de la base de données: {str(e)}")
            raise

# 4. AJOUTER cette fonction dans app.py
def create_default_admin():
    """Créer un utilisateur admin par défaut sur Render"""
    try:
        # Vérifier si un admin existe déjà
        admin_user = LocalUser.query.filter_by(email="admin@linkedboost.com").first()
        
        if not admin_user:
            admin_user = LocalUser(
                email="admin@linkedboost.com",
                first_name="Admin",
                last_name="LinkedBoost",
                company="LinkedBoost",
                job_title="Administrateur",
                is_verified=True
            )
            admin_user.set_password("AdminLinkedBoost2025!")
            
            db.session.add(admin_user)
            db.session.commit()
            
            logger.info("✅ Utilisateur admin créé sur Render")
            logger.info("📧 Email: admin@linkedboost.com")
            logger.info("🔐 Password: AdminLinkedBoost2025!")
        else:
            logger.info("ℹ️ Utilisateur admin déjà existant")
            
    except Exception as e:
        logger.error(f"❌ Erreur lors de la création de l'admin: {str(e)}")

# 5. MODIFIER votre render.yaml
services:
  - type: web
    name: linkedin-boost
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: linkedboost-db
          property: connectionString
      - key: RENDER
        value: "true"  # 👈 Pour détecter l'environnement Render
      - key: FLASK_ENV
        value: "production"
      - key: FLASK_DEBUG
        value: "0"
      - key: LINKEDIN_CLIENT_ID
        value: 86occjps58doir
      - key: LINKEDIN_CLIENT_SECRET
        value: WPL_AP1.C8C6uXjTbpJyQUx2.Y7COPg==
      - key: LINKEDIN_REDIRECT_URI
        value: https://linkedinboost.onrender.com/callback
      - key: GEMINI_API_KEY
        value: AIzaSyB434P__wR_o_rr5Q3PjOULqyKhMANRtgk

databases:
  - name: linkedboost-db
    databaseName: boostdb_taut
    user: boostdb_taut_user
    region: frankfurt
    plan: free
